export const bugNames = [
  "Lesser Hive Mind",
  "Hive Network",
  "Neural Cluster",
  "Hive Neuron",
  "Neuroprophet",
  "Hive Empress",
  "Hive Queen",
  "Hive",
  "Greater Queen",
  "Nest",
  "Queen",
  "Drone",
  "Meat",
];
export const bugs = [
  "Drone",
  "Queen",
  "Nest",
  "Greater Queen",
  "Hive",
  "Hive Queen",
  "Hive Empress",
  "Neuroprophet",
  "Hive Neuron",
  "Neural Cluster",
  "Hive Network",
  "Lesser Hive Mind",
];

export const UNITS = [
  "",
  "K",
  "M",
  "B",
  "T",
  "Qa",
  "Qi",
  "Sx",
  "Sp",
  "Oc",
  "No",
  "Dc",
  "UDc",
  "DDc",
  "TDc",
  "QaDc",
  "QiDc",
  "SxDc",
  "SpDc",
  "ODc",
  "NDc",
  "Vi",
  "UVi",
  "DVi",
  "TVi",
  "QaVi",
  "QiVi",
  "SxVi",
  "SpVi",
  "OVi",
  "NVi",
  "Tg",
  "UTg",
  "DTg",
  "TTg",
  "QaTg",
  "QiTg",
  "SxTg",
  "SpTg",
  "OTg",
  "NTg",
  "Qd",
  "UQd",
  "DQd",
  "TQd",
  "QaQd",
  "QiQd",
  "SxQd",
  "SpQd",
  "OQd",
  "NQd",
];

export const LONGUNITS = {
  "": "",
  K: "thousand",
  M: "million",
  B: "billion",
  T: "trillion",
  Qa: "quadrillion",
  Qi: "quintillion",
  Sx: "sextillion",
  Sp: "septillion",
  Oc: "octillion",
  No: "nonillion",
  Dc: "decillion",
  UDc: "undecillion",
  DDc: "duodecillion",
  TDc: "tredecillion",
  QaDc: "quattuordecillion",
  QiDc: "quinquadecillion",
  SxDc: "sedecillion",
  SpDc: "septendecillion",
  ODc: "octodecillion",
  NDc: "novendecillion",
  Vi: "vigintillion",
  UVi: "unvigintillion",
  DVi: "duovigintillion",
  TVi: "tresvigintillion",
  QaVi: "quattuorvigintillion",
  QiVi: "quinquavigintillion",
  SxVi: "sesvigintillion",
  SpVi: "septemvigintillion",
  OVi: "octovigintillion",
  NVi: "novemvigintillion",
  Tg: "trigintillion",
  UTg: "untrigintillion",
  DTg: "duotrigintillion",
  TTg: "trestigintillion",
  QaTg: "quattuortrigintillion",
  QiTg: "quinquatrigintillion",
  SxTg: "sestrigintillion",
  SpTg: "septentrigintillion",
  OTg: "octotrigintillion",
  NTg: "noventrigintillion",
  Qd: "quadragintillion",
  UQd: "unquadragintillion",
  DQd: "duoquadragintillion",
  TQd: "tresquadragintillion",
  QaQd: "quattuorquadragintillion",
  QiQd: "quinquaqudragintillion",
  SxQd: "sesquadragintillion",
  SpQd: "septenquadragintillion",
  OQd: "octoquadragintillion",
  NQd: "novenquadragintillion",
};

export const bugCards = {
  Meat: {
    description: "All of your swarm's creatures eat meat.",
  },
  Drone: {
    description:
      "Drones are the lowest class of worker in your swarm. They continuously gather meat to feed your swarm.",
    cost: 0,
    costMeat: 10,
    production: 1,
    parent: "Queen",
    child: "Meat",
  },
  Queen: {
    description: "Queens rule over your swarm's workers.",
    cost: 100,
    costMeat: 810,
    production: 2,
    parent: "Nest",
    child: "Drone",
  },
  Nest: {
    description: "Nests provide space and support for your swarm's queens.",
    cost: 1000,
    costMeat: 72900,
    production: 3,
    parent: "Greater Queen",
    child: "Queen",
  },
  "Greater Queen": {
    description:
      "Greater Queens rule over the lesser queens of very large swarms.",
    cost: 10000,
    costMeat: 6.56e6,
    production: 4,
    parent: "Hive",
    child: "Nest",
  },
  Hive: {
    description:
      "Hives are huge structures crafted from meat and the bodies of thousands of queens. They allow your swarm to grow even faster.",
    cost: 1e5,
    costMeat: 59e7,
    production: 5,
    parent: "Hive Queen",
    child: "Greater Queen",
  },
  "Hive Queen": {
    description:
      "Hive queens oversee the production of hives in the largest swarms.",
    cost: 1e6,
    costMeat: 53.1e9,
    production: 6,
    parent: "Hive Empress",
    child: "Hive",
  },
  "Hive Empress": {
    description: "The mightiest creature to rule over your swarm so far.",
    cost: 10e6,
    costMeat: 4.78e12,
    production: 7,
    parent: "Neuroprophet",
    child: "Hive Queen",
  },
  Neuroprophet: {
    description:
      "Your prophets foresee the guidance of a higher power, a greater being - yet, the heavens have fallen silent.",
    cost: 100e6,
    costMeat: 430e12,
    production: 8,
    parent: "Hive Neuron",
    child: "Hive Empress",
  },
  "Hive Neuron": {
    description: "Neurons are the building blocks of a greater intelligence.",
    cost: 1e9,
    costMeat: 38.7e15,
    production: 9,
    parent: "Neural Cluster",
    child: "Neuroprophet",
  },
  "Neural Cluster": {
    description:
      "Groups of neurons begin to exert mild psychic powers, influencing the minds of lesser creatures in your swarm.",
    cost: 10e9,
    costMeat: 3.48e18,
    production: 10,
    parent: "Hive Network",
    child: "Hive Neuron",
  },
  "Hive Network": {
    description:
      "Networking your hive's neurons allows them to coordinate their actions, much as a single entity would.",
    cost: 1e12,
    costMeat: 313e18,
    production: 11,
    parent: "Lesser Hive Mind",
    child: "Neural Cluster",
  },
  "Lesser Hive Mind": {
    description:
      "Your neural networks have finally formed a single greater intelligence, primitive though it may be. The psychic powers of lesser hive minds are great enough to directly control several hundred lesser members of your swarm.",
    cost: 100e12,
    costMeat: 28.2e21,
    production: 12,
    child: "Hive Network",
  },
};
